In [71]:
import numpy as np
from pystruct.datasets import load_letters
letters = load_letters()
X, y = letters['data'], letters['labels']
X, y = np.array(X), np.array(y)

In [72]:
np.unique(np.concatenate([np.unique(yi) for yi in y]))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
y

array([array([14, 12, 12,  0, 13,  3,  8, 13,  6]),
       array([14, 12, 12,  0, 13,  3,  8, 13,  6]),
       array([14, 12, 12,  0, 13,  3,  8, 13,  6]), ...,
       array([13,  2, 14, 13, 18,  4, 16, 20,  4, 13, 19,  8,  0, 11]),
       array([13,  2, 14, 13, 18,  4, 16, 20,  4, 13, 19,  8,  0, 11]),
       array([13,  2, 14, 13, 18,  4, 16, 20,  4, 13, 19,  8,  0, 11])], dtype=object)

In [211]:
def splitWord(feature, label, window):
    feature = np.array(feature)
    label = np.array(label).reshape(-1,1)
    
    num_letters = feature.shape[0]
    letter_features = feature.shape[1]
    
    feature_splits = []
    label_splits = []
    if num_letters < window:
        features_to_append = np.zeros((window - num_letters, letter_features))
        labels_to_append = np.array([26 for i in range(window - num_letters)]).reshape((-1,1))
        
        feature_split = (np.vstack((feature, features_to_append)))
        label_split = (np.vstack((label, labels_to_append)))
        
        feature_splits.append(feature_split)
        label_splits.append(label_split)
    else: 
        for i in range(num_letters - window + 1):
            feature_split = feature[i:(i+window)]
            label_split = label[i:(i+window)]
            
            feature_splits.append(feature_split)
            label_splits.append(label_split)
    return(np.array(feature_splits), np.array(label_splits))                    

In [212]:
def splitWords(features, labels, window):
    feature_splits, label_splits = zip(*list(map(lambda x, y: splitWord(x,y,window), features, labels)))
    feature_splits = np.vstack(feature_splits)
    label_splits = np.vstack(label_splits)
    return(feature_splits, label_splits)

In [213]:
def selectWordsByLetters(words, start, stop):
    i = 0
    newWords = []
    for word in words:
        newWord = []
        for letter in word:
            if i >= start:
                if i < stop:
                    newWord.append(letter)
                else:
                    if newWord:
                        newWords.append(np.array(newWord))
                    return(np.array(newWords))
            i = i + 1
        if newWord:
            newWords.append(np.array(newWord))

In [214]:
train_word_features = selectWordsByLetters(X, 0, 4000)
train_word_labels = selectWordsByLetters(y, 0, 4000)

test_word_features = selectWordsByLetters(X, 4000, 5000)
test_word_labels = selectWordsByLetters(y, 4000, 5000)

In [218]:
#Test to see if lengths are correct
sum([len(entry) for entry in train_word_labels])

4000

In [217]:
#Test to see if lengths are correct
sum([len(entry) for entry in test_word_labels])

1000

In [220]:
#Window size:
window = 2

In [221]:
X_train, y_train = splitWords(train_word_features, train_word_labels, window)

In [222]:
X_train.shape

(3519, 2, 128)

In [223]:
y_train.shape

(3519, 2, 1)