In [1]:
import re
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
%matplotlib inline
import csv
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()
onehot_encoder= OneHotEncoder(sparse=False)

In [4]:
def iors(s):
    try:
        return int(s)
    except ValueError: # if it is a string, return a string
        return s

In [5]:
def read_POS(filename, n_examples, n_features):
    dataset={}
    dataset['sentence_ids']=np.zeros(n_examples, dtype=int)
    dataset['token_ids'] = np.zeros(n_examples, dtype=int)
    dataset['tokenIdDic'] = {}
    dataset['pos'] = [] # It is another dictionary
    dataset['posDic'] = {}
    
    
    with open(filename, 'rb') as csvfile:
        csvreader = csv.reader(csvfile, delimiter=',')
        csvreader.next() # skip the first line sentence_id, token_id, pos
        
        i =0
        for str_line in csvreader:
            line0 = map(iors, str_line)

            dataset['pos'].append(line0.pop())
            dataset['token_ids'][i] = line0.pop()
            dataset['sentence_ids'][i] = line0.pop()

            if dataset['token_ids'][i] in dataset['tokenIdDic']:
                dataset['tokenIdDic'][dataset['token_ids'][i]] += 1
            else:
                dataset['tokenIdDic'][dataset['token_ids'][i]] = 1

            if dataset['pos'][-1] in dataset['posDic']:
                dataset['posDic'][dataset['pos'][-1]] += 1
            else:
                dataset['posDic'][dataset['pos'][-1]] = 1

            #print ' '.join(row)
            i+=1
            if i == n_examples:
                break
        
        dataset['labels'] = integer_encoded = label_encoder.fit_transform(dataset['pos'])
        dataset['features'] = onehot_encoder.fit_transform(dataset['token_ids'].reshape(-1,1))
    
    csvfile.close()
    return dataset


In [6]:
dataset2 = read_POS('POSdataset/pos_tags.csv', 10, 1)

In [7]:
print dataset2['pos'][:10]

['NNP', 'VBZ', 'DT', 'NN', 'IN', 'NN', 'IN', 'NN', 'NNP', 'NNP']


In [8]:
print dataset2['labels'][:10]
print label_encoder.inverse_transform(dataset2['labels'][:10])

[3 4 0 2 1 2 1 2 3 3]
['NNP' 'VBZ' 'DT' 'NN' 'IN' 'NN' 'IN' 'NN' 'NNP' 'NNP']


/home/james/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [9]:
print dataset2['features']
print max(dataset2['token_ids'])
print min(dataset2['token_ids'])
print dataset2['tokenIdDic']
print

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]]
8
0
{0: 1, 1: 1, 2: 2, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1}



In [122]:
print dataset2['posDic']

{'VBZ': 1, 'DT': 1, 'IN': 2, 'NN': 3, 'NNP': 3}
